export { run, type RunOptions } from './run.js';
export { createWatcher, watchPlugins, type WatcherOptions } from './watcher.js';
export { handleLspMessage, initializeResult, completionItems, type LspMessage } from './lsp.js';
export { normalizeAutocompleteShell, renderAutocompleteScript, type AutocompleteShell } from './autocomplete.js';

// App-facing re-exports: `import { Command } from '@mudah-cli/mudah'` is all users need.
export { Command } from '@mudah-cli/console';
export {
  Application,
  EventBus,
  ServiceProvider,
  UsageError,
  ExitError,
  CommandCancelled,
  addMessages,
  checkForUpdate,
  clearUpdateCache,
  compareSemVer,
  createTelemetry,
  defaultCacheDir,
  defaultMigrationTable,
  discoverPlugins,
  findPluginPackages,
  formatGraph,
  formatUpdateNudge,
  gatePlugin,
  loadManifest,
  loadPlugin,
  MigrationRunner,
  parseSemVer,
  pluginGraph,
  setLocale,
  t,
  type MudahManifest,
  type LazyProviderOptions,
  type Migration,
  type PluginDiscoveryOptions,
  type PluginInfo,
  type ProviderClass,
  type AppEvents,
  type Telemetry,
  type TelemetrySink,
  type UpdateCheckOptions,
  type UpdateCheckResult,
} from '@mudah-cli/core';
export {
  ConfigRepository,
  ConfigValidationError,
  SecretStore,
  assertSchema,
  createSecretStore,
  defineConfig,
  envSecretDriver,
  fileSecretDriver,
  formatPrecedence,
  installConfigReloadSignal,
  keyringSecretDriver,
  loadRemoteConfig,
  redactSecrets,
  REDACT_KEYS,
  resolveSecret,
  type RedactOptions,
  env,
  loadEnvFile,
  loadConfigFiles,
  s,
  schemaAt,
  validateSchema,
  watchConfig,
  type ConfigLayer,
  type ConfigSource,
  type PrecedenceRow,
  type Schema,
  type SchemaIssue,
  type SchemaResult,
} from '@mudah-cli/config';
export { Container } from '@mudah-cli/container';
export { detectCapabilities, type TerminalCapabilities } from '@mudah-cli/terminal';
